name = "HollvedRegistry"
uuid = "1d8b4946-ae46-4010-9608-f53c54bdaa7f"
repo = "https://github.com/epolack/HollvedRegistry.jl"

[packages]
498d8bb8-48f6-584d-8f05-fccc9a211def = { name = "ABINIT_jll", path = "jll/A/ABINIT_jll" }
